# Generated by Django 3.0.7 on 2020-06-18 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0002_auto_20200618_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='day',
            field=models.CharField(default=3, max_length=3),
            preserve_default=False,
        ),
    ]
