# Generated by Django 3.0.7 on 2020-06-18 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0003_auto_20200619_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='machine',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='patient',
            name='session',
            field=models.CharField(default=3, max_length=3),
            preserve_default=False,
        ),
    ]
