# Generated by Django 3.0.7 on 2020-06-19 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0004_auto_20200619_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='session',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
