# Generated by Django 3.0.7 on 2020-06-19 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0006_auto_20200619_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='machine',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
